---
name: Nightly build CI

on:
  push:
    paths:
      - .github/workflows/nightly.yml
      - Dockerfile.client.production
      - Dockerfile.server.production
      - apps/client/**
      - apps/server/**
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push client nightly
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.client.production
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yooooomi/your_spotify_client:nightly
            yooooomi/your_spotify_client:${{ github.sha }}

      - name: Build and push server nightly
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server.production
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yooooomi/your_spotify_server:nightly
            yooooomi/your_spotify_server:${{ github.sha }}
